package app;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;

import java.net.URL;
import java.sql.*;
import java.util.ResourceBundle;

public class AddEquipmentController implements Initializable{

    @FXML private Button saveButton;

    @FXML private TextField name;
    @FXML private TextArea description;

    public void saveEquipment(ActionEvent event){

        if (!name.getText().isEmpty() && ! description.getText().isEmpty()){

            try {
                Connection con = DBConnector.getConnection();
                PreparedStatement stm = con.prepareStatement("INSERT INTO Equipment (name, description) VALUES(?,?)", Statement.RETURN_GENERATED_KEYS);
                stm.setString(1, name.getText());
                stm.setString(2, description.getText());
                stm.execute();

                ResultSet rs = stm.getGeneratedKeys();
                rs.next();
                int autoGeneratedID = rs.getInt(1);
                stm.close();
                System.out.println("Inserted: " + name.getText() + " : " + description.getText());
                System.out.println(autoGeneratedID);



            } catch (SQLException e) {
                e.printStackTrace();
            }

            finally {
                saveButton.getScene().getWindow().hide();
            }
        }


    }




    @Override
    public void initialize(URL location, ResourceBundle resources) {

    }
}
