package app;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;

import java.net.URL;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.ResourceBundle;

public class NewWorkoutController implements Initializable{

    @FXML DatePicker datePicker;
    @FXML TextField timeTextField;
    @FXML Spinner<Integer> durationSpinner = new Spinner<>();
    @FXML Spinner<Integer> shapeSpinner = new Spinner<>();
    @FXML Spinner<Integer> performanceSpinner = new Spinner<>();
    @FXML TextArea noteTextArea;
    @FXML Button createButton;
    @FXML Button discardButton;

    public void discardButtonPressed() {
        datePicker.setValue(LocalDate.now());
        timeTextField.clear();
        durationSpinner.getValueFactory().setValue(60);
        shapeSpinner.getValueFactory().setValue(5);
        performanceSpinner.getValueFactory().setValue(5);
        noteTextArea.clear();
    }

    public void createButtonPressed(){

        try {
            Connection con = DBConnector.getConnection();
            PreparedStatement stm = con.prepareStatement("INSERT INTO Workout (workout_date, workout_time, duration, shape, performance, note) VALUES(?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);
            stm.setString(1, datePicker.getValue().toString());
            stm.setString(2, timeTextField.getText());
            stm.setInt(3, durationSpinner.getValue());
            stm.setInt(4, shapeSpinner.getValue());
            stm.setInt(5, performanceSpinner.getValue());
            stm.setString(6, noteTextArea.getText());
            stm.execute();

            ResultSet rs = stm.getGeneratedKeys();
            rs.next();
            int autoGeneratedID = rs.getInt(1);
            stm.close();
            System.out.println("Workout with key: " + autoGeneratedID + " inserted");



        } catch (SQLException e) {
            e.printStackTrace();
        }

        discardButtonPressed(); //to clear input
    }




    @Override
    public void initialize(URL location, ResourceBundle resources) {


        //intitialize input format for new workout
        SpinnerValueFactory<Integer> shapeValueFactory = new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 10, 5);
        SpinnerValueFactory<Integer> performanceValueFactory = new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 10, 5);
        SpinnerValueFactory<Integer> durationValueFactory = new SpinnerValueFactory.IntegerSpinnerValueFactory(5, 480, 60, 5);
        shapeSpinner.setValueFactory(shapeValueFactory);
        performanceSpinner.setValueFactory(performanceValueFactory);
        durationSpinner.setValueFactory(durationValueFactory);

        datePicker.setValue(LocalDate.now());

    }
}
